#!/usr/bin/env python
"""Metric-unification analysis, entirely from `results/raw/*.json`.

No model is loaded and no attribution is computed -- this reads the per-sample
scores the benchmark already wrote and asks what the six metrics of Tables 2-4
actually span.  Runs in seconds.

    python scripts/10_metric_unification.py --model resnet50 --n 200

Writes to `results/unification/`:

    variance_decomposition__<tag>.csv   how much of each metric is about the method
    corr_methods__<tag>.csv             Spearman between metrics over methods
    corr_samples__<tag>.csv             Spearman between metrics over images
    redundancy_methods__<tag>.csv       pairwise, with both significance thresholds
    redundancy_samples__<tag>.csv
    pca_loadings__<tag>.csv             metric loadings on the components
    pca_scores__<tag>.csv               method positions
    pca_explained__<tag>.csv            eigenvalues and cumulative variance
    summary__<tag>.md                   the readable version
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from spx.unify import (  # noqa: E402
    METRIC_ORDER,
    factor_analysis,
    load_raw,
    method_matrix,
    metric_correlation_methods,
    metric_correlation_samples,
    position_of,
    redundancy,
    variance_decomposition,
)

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results" / "unification"

#: the families, used for the subset analyses -- the whole-panel factor
#: structure is partly an artefact of 11 of the 19 methods being variants of
#: each other, so it has to be checked inside each family too.
PULLBACK_FAMILY = [
    "SoftPullback", "DoublePullback", "PullbackAscent", "GradientAscent",
    "DistributionPullback", "DistributionDoublePullback", "DistributionAscent",
    "MarginPullback", "MarginAscent", "MarginAscentFrozen", "MarginGradientAscent",
]
CAPTUM_FAMILY = [
    "Gradient", "Saliency", "InputXGradient", "IntegratedGradients",
    "GradientShap", "DeepLift", "Deconvolution", "GuidedGradCam",
]
HIGHLIGHT = ["SoftPullback", "DistributionPullback", "MarginPullback", "MarginAscent"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="resnet50")
    ap.add_argument("--n", type=int, default=200)
    ap.add_argument("--budget", default="paper")
    ap.add_argument("--out", default=str(OUT))
    a = ap.parse_args()

    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    tag = f"{a.model}__n{a.n}__{a.budget}"

    df = load_raw(a.model, n=a.n, budget=a.budget)
    methods = sorted(df["method"].unique())
    print(f"{len(df)} rows | {len(methods)} methods | {df['sample'].nunique()} images")

    vd = variance_decomposition(df)
    cm = metric_correlation_methods(df)
    cs = metric_correlation_samples(df)
    rm = redundancy(df, "methods")
    rs = redundancy(df, "samples")
    fa = factor_analysis(df)

    vd.to_csv(out / f"variance_decomposition__{tag}.csv")
    cm.to_csv(out / f"corr_methods__{tag}.csv")
    cs.to_csv(out / f"corr_samples__{tag}.csv")
    rm.to_csv(out / f"redundancy_methods__{tag}.csv", index=False)
    rs.to_csv(out / f"redundancy_samples__{tag}.csv", index=False)
    fa["loadings"].to_csv(out / f"pca_loadings__{tag}.csv")
    fa["scores"].to_csv(out / f"pca_scores__{tag}.csv")
    pd.DataFrame({
        "eigenvalue": fa["eigenvalues"],
        "explained": fa["explained"],
        "cumulative": fa["explained"].cumsum(),
    }).to_csv(out / f"pca_explained__{tag}.csv")
    method_matrix(df, agg="rank").to_csv(out / f"rank_matrix__{tag}.csv")

    # -- subsets ---------------------------------------------------------
    subs = {}
    for nm, keep in (("pullback", PULLBACK_FAMILY), ("captum", CAPTUM_FAMILY)):
        sub = df[df["method"].isin(keep)]
        if sub["method"].nunique() >= 6:
            f = factor_analysis(sub)
            subs[nm] = f
            f["loadings"].to_csv(out / f"pca_loadings__{nm}__{tag}.csv")
            f["explained"].to_csv(out / f"pca_explained__{nm}__{tag}.csv")

    # -- the readable version -------------------------------------------
    L = []
    L.append(f"# Metric unification -- {a.model}, n = {a.n}\n")
    L.append(
        "Generated by `scripts/10_metric_unification.py` from `results/raw/*.json`. "
        "Every aggregate is rank-based: `Infidelity` spans fifteen orders of "
        "magnitude across methods, so means and Pearson correlations over it are "
        "reports on `Deconvolution`'s tail.\n"
    )

    L.append("\n## 1. How much of each metric is about the method at all\n")
    L.append(
        "Two-way variance decomposition of the rank-transformed method x image "
        "panel. `var_method` is the share of variance attributable to which "
        "method produced the map.\n"
    )
    L.append(vd.round(3).to_markdown())
    weak = vd.index[vd["var_method"] < 0.10].tolist()
    if weak:
        L.append(
            f"\n**{', '.join(weak)}** put under 10 % of their variance on the method. "
            "Differences between adjacent methods on those columns of "
            "`results/RESULTS.md` are not resolved by n = 200, and the marginal "
            "`mean +/- std` presentation hides that.\n"
        )

    L.append("\n## 2. Do the metrics agree about methods?\n")
    L.append(cm.round(2).to_markdown())
    L.append("\n\n### Pairwise, with thresholds\n")
    L.append(rm.round(3).to_markdown(index=False))
    L.append(
        f"\n\nSurviving Bonferroni over the 15 pairs: "
        f"**{', '.join(f'{r.a}~{r.b}' for r in rm.itertuples() if r.sig_bonf) or 'none'}**.\n"
    )

    L.append("\n## 3. Do the metrics agree about images?\n")
    L.append(
        "Spearman over the images *inside* each method, pooled by Fisher-z. "
        "This is the powered version of the question -- n = images, not "
        "n = 19 methods.\n"
    )
    L.append(cs.round(2).to_markdown())
    L.append("\n\n" + rs.round(3).to_markdown(index=False))
    L.append(
        f"\n\nSurviving Bonferroni: "
        f"**{', '.join(f'{r.a}~{r.b}' for r in rs.itertuples() if r.sig_bonf) or 'none'}**. "
        "Largest |rho| at image level is "
        f"{rs['abs_rho'].max():.3f} against {rm['abs_rho'].max():.3f} at method level.\n"
    )

    L.append("\n## 4. How many axes do the six span?\n")
    L.append(
        pd.DataFrame({
            "eigenvalue": fa["eigenvalues"],
            "explained": fa["explained"],
            "cumulative": fa["explained"].cumsum(),
        }).round(3).to_markdown()
    )
    L.append(
        f"\n\nKaiser criterion: **{fa['kaiser']}** components. "
        f"80 % of variance needs **{fa['n_for_80']}**, 90 % needs **{fa['n_for_90']}**.\n"
    )
    L.append("\n### Loadings\n")
    L.append(fa["loadings"].round(2).to_markdown())
    L.append(
        "\n\nRanks are oriented so higher = better, so a positive loading means "
        "the component agrees with that metric's own notion of quality.\n"
    )
    L.append("\n### Method positions\n")
    L.append(fa["scores"].round(2).sort_values("PC1", ascending=False).to_markdown())

    for nm, f in subs.items():
        L.append(f"\n### Within the {nm} family only\n")
        L.append(
            f"{f['explained'].round(3).tolist()} explained; Kaiser {f['kaiser']}, "
            f"80 % at {f['n_for_80']}.\n\n"
        )
        L.append(f["loadings"].round(2).iloc[:, :2].to_markdown())
        L.append("\n")

    have = [m for m in HIGHLIGHT if m in fa["scores"].index]
    if have:
        L.append("\n## 5. Where the extensions sit\n")
        L.append(position_of(fa, have, k=3).round(2).to_markdown())

    (out / f"summary__{tag}.md").write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {out / f'summary__{tag}.md'}")


if __name__ == "__main__":
    main()
